[package]
name = "relm4-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
relm4 = "0.5.1"
relm4-components = "0.5.1"
tracker = "0.2.1"
